# TODO 是否需要持续发布？持续发布会引起一些问题，比如：1. 如果写了BUG, 会自动被引入到业务系统中(如何是SNAPSHOT); 2. 如果采用发行版，那每次递增版本也过于频繁了。
#---
#kind: pipeline
#type: docker
#name: db-metadata 发布到maven 私服
#
#steps:
#  # 添加认证信息
#  - name: authenticate
#    image: robertstettner/drone-mvn-auth
#    pull: always
#    settings:
#      servers:
#        - id: asoco-nexus-release
#          username: admin
#          password: hthj.m2
#        - id: asoco-nexus-snapshot
#          username: admin
#          password: hthj.m2
#    when:
#      branch:
#        - spring-boot
#
#  # 打包发布到nexus仓库中
#  - name: deploy-to-nexus
#    image: maven:3-alpine
#    commands:
#      - mvn -f db-metadata-parent/pom.xml -DskipTests clean deploy -gs settings.xml
#    when:
#      branch:
#        - spring-boot
#
#trigger:
#  ref:
#    - refs/heads/spring-boot
