spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/db-metadata-demo?useSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


logging:
  level:
    mb: debug
    root: info
  group:
    mb: com.github.md.web

md:
  dev-mode: true
  analysis:
    source-config:
      db-metadata-business-demo:
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/db-metadata-business-demo?useSSL=false&characterEncoding=utf-8
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
  server:
    meta-object:
      replace-from-json-file: true
    component:
      replace-from-json-file: true
    upload:
      mode: local # default, 可以不配置
      base-upload-path: /opt/www/db-meta-serve # 当mode为本地时，配置的本地上传根路径