spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/metadata?useSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


logging:
  level:
    mb: debug
    root: info
  group:
    mb: com.github.md.web

md:
  dev-mode: true
